module Tempest
  class Error < StandardError
  end

  class AuthenticationError < Error
    attr_reader code: Integer?

    def initialize: (String message, ?code: Integer?) -> void
  end

  class APIError < Error
    attr_reader status: Integer
    attr_reader body: untyped

    def initialize: (Integer status, untyped body) -> void
  end
end
